import { FaBolt, FaCampground, FaLightbulb, FaCamera, FaPalette } from "react-icons/fa";

export const rentalsData = [
  {
    id: 1,
    title: "Generator",
    icon: <FaBolt className="w-6 h-6 text-white" />,
    description: "Power up your events with our reliable generators.",
    fullDescription: "Ensure your event never goes dark with our premium 5kVA to 10kVA silent generators. Perfect for weddings, corporate retreats, and outdoor festivals in remote locations. Our units are regularly serviced and come with a full tank of fuel and 24/7 technical support.",
    image: "/generator.webp",
    category: "Power Solutions",
    rating: 4.9,
    reviews: 45,
    price: "₹2,500/day",
    features: ["Silent Operation", "Fuel Efficient", "24/7 Support", "Automatic Voltage Regulation", "Compact & Portable"],
    popular: true,
    gradient: "from-yellow-400 to-orange-500",
  },
  {
    id: 2,
    title: "Tents",
    icon: <FaCampground className="w-6 h-6 text-white" />,
    description: "Spacious and durable tents for all your outdoor needs.",
    fullDescription: "Our premium event tents offer superior weather protection and exquisite aesthetics for your special occasions. We specialize in beautifully decorated tents for weddings and functions, featuring integrated professional stages and elegant interiors. Made from high-grade PVC material that is 100% waterproof and UV resistant.",
    image: "/Tent-img.jpg",
    category: "Shelter & Comfort",
    rating: 4.8,
    reviews: 62,
    price: "₹3,000/day",
    features: ["Decorated Tents", "Integrated Stage", "Function Ready", "UV Protection", "Elegant Interior"],
    popular: false,
    gradient: "from-green-400 to-emerald-500",
  },
  {
    id: 3,
    title: "Lighting System",
    icon: <FaLightbulb className="w-6 h-6 text-white" />,
    description: "Brighten up your events with our professional lighting systems.",
    fullDescription: "Transform your marriage and event venues with our comprehensive lighting decor solutions. We provide high-end LED PAR cans, moving heads, and ambient string lights tailored for wedding decorations. Our professional lighting decors create the perfect atmosphere for your special night.",
    image: "/Lighting Decoration.jpg",
    category: "Ambiance & Decor",
    rating: 4.9,
    reviews: 38,
    price: "₹1,800/day",
    features: ["Marriage Decor", "Event Lighting", "Remote Control", "Dimmable", "Premium Atmosphere"],
    popular: true,
    gradient: "from-purple-400 to-pink-500",
  },
  {
    id: 4,
    title: "DSLR Camera",
    icon: <FaCamera className="w-6 h-6 text-white" />,
    description: "Capture every moment with our high-quality DSLR cameras.",
    fullDescription: "Professional grade photography equipment for capturing your most precious moments. Our kits include the latest full-frame bodies, a 24-70mm f/2.8 lens, and high-speed memory cards. Suitable for both professional photographers and hobbyists.",
    image: "/Dslr.avif",
    category: "Photography",
    rating: 4.7,
    reviews: 29,
    price: "₹500/day",
    features: ["4K Video", "Professional Lens", "Memory Card Included", "Camera Stand (Tripod)", "Camera Bag"],
    popular: false,
    gradient: "from-blue-400 to-cyan-500",
  },
  {
    id: 5,
    title: "Camping Equipment",
    icon: <FaCampground className="w-6 h-6 text-white" />,
    description: "Professional gear including small tents, lighting, and essentials for your adventures.",
    fullDescription: "Embark on an unforgettable adventure with our premium camping gear. This set includes a lightweight, 2-person waterproof tent, a high-intensity LED lantern, and a portable cooking stove. All gear is ultralight and designed for easy transport in difficult terrain.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=1470&auto=format&fit=crop",
    category: "Outdoor & Adventure",
    rating: 4.9,
    reviews: 18,
    price: "₹1,500/day",
    features: ["Small Tent", "Camping Lights", "Portable Stove", "Ground Mat", "Waterproof Bag"],
    popular: false,
    gradient: "from-teal-400 to-green-500",
  },
  {
    id: 6,
    title: "Event Decoration",
    icon: <FaPalette className="w-6 h-6 text-white" />,
    description: "Complete aesthetic transformation for your special occasions.",
    fullDescription: "Our event decoration service provides a total artistic transformation of your venue. From grand wedding stages to intimate corporate setups, we use premium fabrics, floral arrangements, and thematic elements to create an unforgettable atmosphere. Every detail is curated to match your vision, ensuring a breathtaking experience for your guests in Kupwara.",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1470&auto=format&fit=crop",
    category: "Ambiance & Decor",
    rating: 4.8,
    reviews: 32,
    price: "₹5,000/start",
    features: ["Wedding Stages", "Floral Decor", "Theme Parties", "Premium Fabrics", "Lighting Accents"],
    popular: true,
    gradient: "from-pink-400 to-rose-600",
  },
];
